import Link from "next/link";
import { ArrowRight, CheckCircle2, Layers3, ScanSearch, ShieldAlert, WalletCards } from "lucide-react";
import { Button } from "@/components/ui/Button";

const steps = [["01", "Connect", "Bring your investments together."], ["02", "X-Ray", "Look through every layer of your portfolio."], ["03", "Diagnose", "Find hidden concentration, overlap and fees."], ["04", "Investigate", "Understand where your portfolio can improve."]];
const features = [
  { Icon: ScanSearch, title: "Portfolio X-Ray", text: "See underlying company, group and sector exposure—not just the funds you bought." },
  { Icon: Layers3, title: "Overlap & fees", text: "Identify duplicate positions and potential fee inefficiency across mutual funds." },
  { Icon: WalletCards, title: "Scenario analysis", text: "Explore historical and what-if portfolio scenarios with clear, non-guaranteed estimates." },
];

export default function LandingPage() {
  return <main className="min-h-screen bg-background text-foreground">
    <nav className="mx-auto flex h-16 max-w-7xl items-center justify-between border-b border-border px-5"><Link href="/" className="flex items-center gap-2"><span className="grid h-7 w-7 place-items-center rounded bg-primary text-sm font-bold text-white">N</span><span className="text-sm font-semibold">Nivesh Lens</span></Link><div className="flex gap-2"><Link href="/login"><Button size="sm" variant="ghost">Sign in</Button></Link><Link href="/login?tab=signup"><Button size="sm">Connect portfolio</Button></Link></div></nav>
    <section className="mx-auto grid max-w-7xl gap-10 px-5 py-16 lg:grid-cols-[1fr_.9fr] lg:py-24"><div className="max-w-2xl"><p className="text-xs font-semibold uppercase tracking-[.18em] text-primary">Portfolio intelligence for India</p><h1 className="mt-5 text-4xl font-semibold leading-tight tracking-tight sm:text-6xl">See what your portfolio is really exposed to.</h1><p className="mt-5 max-w-xl text-base leading-7 text-muted">Nivesh Lens looks through your stocks, mutual funds, FDs and retirement investments to uncover hidden concentration, duplicate exposure, fees and portfolio risks.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/login?tab=signup"><Button size="lg">Analyze my portfolio <ArrowRight className="ml-2 h-4 w-4" /></Button></Link><Link href="/portfolio-xray"><Button variant="outline" size="lg">Explore Portfolio X-Ray</Button></Link></div><p className="mt-5 text-xs text-muted">For analysis and education. Nivesh Lens does not execute trades or provide guaranteed outcomes.</p></div>
      <div className="border border-border bg-card p-4 shadow-2xl shadow-black/20 sm:p-5"><div className="flex items-center justify-between border-b border-border pb-3"><div className="flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-success"/><span className="text-xs text-muted">Portfolio health · sample view</span></div><span className="font-mono text-xs text-success">742 / 900</span></div><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded border border-border bg-background p-3"><p className="text-[10px] uppercase tracking-wider text-muted">Total portfolio</p><p className="mt-2 font-mono text-xl">₹12,48,320</p><p className="mt-1 text-xs text-success">+15.37%</p></div><div className="rounded border border-border bg-background p-3"><p className="text-[10px] uppercase tracking-wider text-muted">Risk level</p><p className="mt-2 text-xl font-semibold text-warning">Moderate</p><p className="mt-1 text-xs text-muted">Sector concentration</p></div></div><div className="mt-4 rounded border border-danger/30 bg-danger/5 p-3"><div className="flex items-center gap-2 text-xs font-semibold text-danger"><ShieldAlert className="h-4 w-4" /> Attention required</div><p className="mt-2 text-sm">Reliance exposure is 26.4%</p><p className="mt-1 text-xs text-muted">Includes direct holdings and mutual fund look-through.</p></div><div className="mt-4 space-y-3">{[["Reliance Industries",26.4],["HDFC Group",18.7],["Tata Group",15.3]].map(([company,value]) => <div key={String(company)}><div className="flex justify-between text-xs"><span>{company}</span><span className="font-mono">{value}%</span></div><div className="mt-1 h-1.5 bg-accent"><div className="h-full bg-primary" style={{width:`${Number(value)*3}%`}} /></div></div>)}</div></div></section>
    <section className="border-y border-border bg-card/50"><div className="mx-auto max-w-7xl px-5 py-12"><p className="text-xs font-semibold uppercase tracking-[.16em] text-muted">How Nivesh Lens works</p><div className="mt-7 grid gap-6 md:grid-cols-4">{steps.map(([number,title,text]) => <div key={number} className="border-l border-border pl-4"><span className="font-mono text-xs text-primary">{number}</span><h2 className="mt-3 text-lg font-semibold">{title}</h2><p className="mt-2 text-sm text-muted">{text}</p></div>)}</div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-16"><div className="grid gap-5 md:grid-cols-3">{features.map(({ Icon, title, text }) => <div key={title} className="border border-border bg-card p-5"><Icon className="h-5 w-5 text-primary" /><h2 className="mt-4 text-base font-semibold">{title}</h2><p className="mt-2 text-sm leading-6 text-muted">{text}</p></div>)}</div></section>
    <footer className="border-t border-border px-5 py-6 text-center text-xs text-muted">© {new Date().getFullYear()} Nivesh Lens · Portfolio analysis, not investment advice.</footer>
  </main>;
}
