"use client";

import { useState } from "react";
import { ArrowRight, Info, SlidersHorizontal } from "lucide-react";
import { Card, CardContent } from "@/components/ui/Card";
import { Button } from "@/components/ui/Button";
import { InsightFlag } from "@/components/ui/InsightFlag";
import { cn } from "@/lib/utils";

type WorkspaceKind = "xray" | "holdings" | "mutualFunds" | "risk" | "stress" | "simulator" | "tax" | "sip" | "family" | "news" | "dividends" | "audit" | "macro" | "alerts" | "api";

const pageCopy: Record<WorkspaceKind, [string, string]> = {
  xray: ["Your Portfolio, Under the Lens", "Look through every layer of your investments to uncover exposure you cannot see from the surface."],
  holdings: ["Holdings", "A terminal-style view of every instrument in your connected portfolio."],
  mutualFunds: ["Mutual Funds", "Scheme health, SIP status, expenses and underlying overlap."],
  risk: ["Risk Analysis", "Measure the factors shaping your portfolio’s downside sensitivity."],
  stress: ["What happens if the market crashes?", "Historical scenario simulation — not a forecast or a guaranteed outcome."],
  simulator: ["Build a Better Portfolio", "Compare structural portfolio changes before you make them."],
  tax: ["Tax Optimizer", "Potential tax-efficiency observations based on your recorded holdings."],
  sip: ["SIP Health", "Keep recurring investments intentional, diversified and on track."],
  family: ["Family Portfolio", "See aggregate household exposure alongside each family member’s portfolio."],
  news: ["News That Matters To Your Portfolio", "Holding-specific events and potential relevance — not a general market feed."],
  dividends: ["Dividend & Passive Income", "Estimated distributions based on sample portfolio holdings."],
  audit: ["Nominee Audit", "Review account nomination records and items that need attention."],
  macro: ["Macro Risk Simulator", "Explore scenario sensitivity. Simulated values are not forecasts."],
  alerts: ["Portfolio Alerts", "Prioritised observations from your portfolio X-Ray."],
  api: ["Portfolio X-Ray API", "Usage, SDK access and diagnostic data endpoints for advisor workflows."],
};

export function FeatureWorkspace({ kind }: { kind: WorkspaceKind }) {
  const [shock, setShock] = useState(30);
  const [query, setQuery] = useState("");
  const [title, subtitle] = pageCopy[kind];
  const isHoldings = kind === "holdings";
  const isStress = kind === "stress" || kind === "macro";
  const isXray = kind === "xray";
  const rows = isHoldings ? [["Reliance Industries", "25", "₹2,410", "₹2,870", "+₹11,500", "+19.08%", "26.4%"], ["HDFC Bank", "40", "₹1,520", "₹1,840", "+₹12,800", "+21.05%", "18.7%"], ["Infosys", "36", "₹1,460", "₹1,560", "+₹3,600", "+6.85%", "5.2%"]] : [["HDFC Flexi Cap", "₹1,68,200", "₹1,96,520", "+16.84%", "0.74%", "42%", "Review"], ["Parag Parikh Flexi Cap", "₹1,46,000", "₹1,71,880", "+17.73%", "0.63%", "42%", "Healthy"], ["Canara Robeco Flexi Cap", "₹1,28,000", "₹1,45,800", "+13.91%", "0.82%", "28%", "Healthy"]];

  return <div className="space-y-5 pb-8">
    <div className="border-b border-border/70 pb-5"><p className="text-[10px] font-semibold uppercase tracking-[0.16em] text-primary">Portfolio intelligence <span className="ml-2 rounded bg-primary/15 px-1.5 py-0.5">SAMPLE DATA</span></p><h1 className="mt-2 text-2xl font-semibold tracking-tight">{title}</h1><p className="mt-1 text-sm text-muted-foreground">{subtitle}</p></div>
    {isStress && <Card className="rounded-lg border-border/80 shadow-none"><CardContent className="grid gap-5 p-5 lg:grid-cols-[1fr_1.4fr]"><div><p className="text-xs font-semibold uppercase tracking-[.14em] text-muted-foreground">Scenario</p><select className="mt-3 h-10 w-full rounded-md border border-border bg-background px-3 text-sm"><option>2008 Financial Crisis</option><option>2020 COVID Crash</option><option>Custom Market Shock</option></select><p className="mt-5 text-xs text-muted-foreground">Market drop</p><input className="mt-2 w-full accent-primary" type="range" min="10" max="50" value={shock} onChange={(event) => setShock(Number(event.target.value))} /><div className="mt-1 flex justify-between font-mono text-xs text-muted-foreground"><span>-10%</span><span className="text-foreground">-{shock}%</span><span>-50%</span></div></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{[["Current portfolio","₹12,48,320","text-foreground"],["Estimated drawdown",`-${(shock * 0.95).toFixed(1)}%`,"text-danger"],["Estimated loss",`-₹${(1248320 * shock * .0095).toLocaleString("en-IN", {maximumFractionDigits:0})}`,"text-danger"],["Recovery estimate","18–26 mo","text-warning"]].map(([label,value,tone]) => <div key={label} className="rounded-md border border-border bg-background p-3"><p className="text-[10px] uppercase tracking-wider text-muted-foreground">{label}</p><p className={cn("mt-2 font-mono text-base font-semibold tabular-nums",tone)}>{value}</p></div>)}</div></CardContent></Card>}
    {kind === "simulator" && <Card className="rounded-lg border-border/80 shadow-none"><CardContent className="grid gap-4 p-5 lg:grid-cols-3"><div><p className="text-xs uppercase tracking-wider text-muted-foreground">Current portfolio</p><p className="mt-2 font-mono text-2xl">742 <span className="text-sm text-muted-foreground">health score</span></p></div><div className="border-y border-border py-4 lg:border-x lg:border-y-0 lg:px-5"><p className="text-xs uppercase tracking-wider text-muted-foreground">Change controls</p><button className="mt-3 flex w-full items-center justify-between rounded-md bg-accent px-3 py-2 text-xs">Reduce financial sector exposure <SlidersHorizontal className="h-3.5 w-3.5" /></button></div><div><p className="text-xs uppercase tracking-wider text-muted-foreground">Projected portfolio</p><p className="mt-2 font-mono text-2xl text-success">801 <span className="text-sm text-muted-foreground">health score</span></p><p className="mt-1 text-xs text-muted-foreground">HHI 0.182 → 0.121 · overlap 42% → 19%</p></div></CardContent></Card>}
    {isXray && <Card className="rounded-lg border-border/80 shadow-none"><CardContent className="p-5"><p className="text-xs font-semibold uppercase tracking-[.14em] text-muted-foreground">Look-through map</p><div className="mt-5 grid gap-2 text-center text-xs font-medium sm:grid-cols-6">{["Portfolio","Mutual funds","Underlying holdings","Companies","Corporate groups","Sector exposure"].map((label, index) => <div key={label} className="flex items-center gap-2 sm:block"><div className="rounded-md border border-border bg-background p-3">{label}</div>{index < 5 && <ArrowRight className="h-3 w-3 text-primary sm:mx-auto sm:mt-2 sm:rotate-0" />}</div>)}</div></CardContent></Card>}
    {kind === "family" && <Card className="rounded-lg border-border/80 shadow-none"><CardContent className="p-5"><div className="grid gap-3 sm:grid-cols-4">{[["You","₹12.4L"],["Parent","₹8.2L"],["Spouse","₹6.1L"],["Family wealth","₹26.7L"]].map(([name,value]) => <div key={name} className="rounded-md border border-border bg-background p-3"><p className="text-xs text-muted-foreground">{name}</p><p className="mt-2 font-mono text-lg">{value}</p></div>)}</div><div className="mt-4 rounded-md border border-warning/30 bg-warning/5 p-3 text-xs"><span className="font-semibold text-warning">Combined Tata Group exposure: 42%</span><span className="ml-2 text-muted-foreground">Your portfolio 15% · Parent 18% · Spouse 9%</span></div></CardContent></Card>}
    {kind === "audit" && <div className="grid gap-4 sm:grid-cols-3">{[["HDFC Bank","Missing","text-danger"],["Zerodha","Added","text-success"],["SBI Mutual Fund","Added","text-success"]].map(([account,status,tone]) => <Card key={account} className="rounded-lg border-border/80 shadow-none"><CardContent className="p-4"><p className="text-xs text-muted-foreground">{account}</p><p className={cn("mt-3 text-sm font-semibold",tone)}>Nominee: {status}</p><Button variant="outline" size="sm" className="mt-4">Review account</Button></CardContent></Card>)}</div>}
    {kind === "news" && <div className="grid gap-3 lg:grid-cols-3">{[["Reliance Industries","Positive","Quarterly earnings beat expectations.","+2.1%"],["HDFC Bank","Neutral","Deposit growth is in line with expectations.","0.4%"],["Infosys","Watch","IT spending commentary may affect near-term sentiment.","-0.8%"]].map(([company,status,reason,impact]) => <Card key={company} className="rounded-lg border-border/80 shadow-none"><CardContent className="p-4"><p className="text-sm font-semibold">{company}</p><p className="mt-2 text-xs text-primary">{status} · potential impact {impact}</p><p className="mt-2 text-xs leading-5 text-muted-foreground">{reason}</p></CardContent></Card>)}</div>}
    {(kind === "tax" || kind === "sip" || kind === "dividends") && <Card className="rounded-lg border-border/80 shadow-none"><CardContent className="grid gap-4 p-5 sm:grid-cols-3">{(kind === "tax" ? [["Tax efficiency","88 / 100"],["Potential loss harvest","₹12,400"],["Tax treatment","Estimate only"]] : kind === "sip" ? [["Active SIPs","7"],["Monthly SIP","₹32,000"],["Needs review","2"]] : [["Estimated annual income","₹48,600"],["Monthly average","₹4,050"],["Upcoming: September","₹4,100"]]).map(([label,value]) => <div key={label} className="rounded-md border border-border bg-background p-3"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-2 font-mono text-xl">{value}</p></div>)}</CardContent></Card>}
    {(isHoldings || kind === "mutualFunds") && <Card className="overflow-hidden rounded-lg border-border/80 shadow-none"><CardContent className="p-0"><div className="flex flex-col gap-3 border-b border-border p-4 sm:flex-row"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search holdings" className="h-9 flex-1 rounded-md border border-border bg-background px-3 text-xs outline-none focus:border-primary" /><Button variant="outline" size="sm">Filters</Button></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-xs"><thead className="bg-accent/60 text-[10px] uppercase tracking-wider text-muted-foreground"><tr>{(isHoldings ? ["Asset","Qty","Avg price","LTP","P&L","P&L %","Exposure"] : ["Scheme","Invested","Current","Returns","TER","Overlap","Health"]).map((head) => <th key={head} className="px-4 py-3 font-medium">{head}</th>)}</tr></thead><tbody>{rows.filter((row) => row[0].toLowerCase().includes(query.toLowerCase())).map((row) => <tr key={row[0]} className="border-t border-border/70 hover:bg-accent/35">{row.map((cell,index) => <td key={`${cell}-${index}`} className={cn("px-4 py-3", String(cell).startsWith("+") && "font-mono text-success", index === 0 && "font-medium text-foreground")}>{cell}</td>)}</tr>)}</tbody></table></div></CardContent></Card>}
    {!["holdings","mutualFunds","stress","macro","simulator","xray","family","audit","news","tax","sip","dividends"].includes(kind) && <InsightFlag severity="warning" headline="Priority portfolio observation" why="Reliance exposure is 26.4% when direct holdings and mutual fund look-through are considered. This is an analytical observation, not a recommendation to buy or sell." fixLabel="Review observation" onFix={() => window.location.href = "/portfolio-xray"} />}
    <p className="flex items-center gap-2 text-[11px] text-muted-foreground"><Info className="h-3.5 w-3.5" /> Sample data for product demonstration. Portfolio analytics and simulations are informational, not investment or tax advice.</p>
  </div>;
}
